In [2]:
import pandas as pd

C:\Users\pedro\AppData\Local\Temp\ipykernel_5108\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [72]:
df = pd.read_csv(".//data//bank.csv", sep=';')

In [73]:
print(df.head())

   age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no
1   33     services  married  secondary      no     4789     yes  yes
2   35   management   single   tertiary      no     1350     yes   no
3   30   management  married   tertiary      no     1476     yes  yes
4   59  blue-collar  married  secondary      no        0     yes   no

    contact  day month  duration  campaign  pdays  previous poutcome   y
0  cellular   19   oct        79         1     -1         0  unknown  no
1  cellular   11   may       220         1    339         4  failure  no
2  cellular   16   apr       185         1    330         1  failure  no
3   unknown    3   jun       199         4     -1         0  unknown  no
4   unknown    5   may       226         1     -1         0  unknown  no

In [75]:
df[["age", "marital"]]

      age  marital
0      30  married
1      33  married
2      35   single
3      30  married
4      59  married
...   ...      ...
4516   33  married
4517   57  married
4518   57  married
4519   28  married
4520   44   single

[4521 rows x 2 columns]

In [10]:
#Filtrando por linhas e colunas
df.loc[0:10, ["age", "job"]]

    age            job
0    30     unemployed
1    33       services
2    35     management
3    30     management
4    59    blue-collar
5    35     management
6    36  self-employed
7    39     technician
8    41   entrepreneur
9    43       services
10   39       services

In [12]:
#O iloc aceita apenas nuemros e não inclui o ultimo do numero da intervalo passado
df.iloc[0:11, 0:3]

    age            job  marital
0    30     unemployed  married
1    33       services  married
2    35     management   single
3    30     management  married
4    59    blue-collar  married
5    35     management   single
6    36  self-employed  married
7    39     technician  married
8    41   entrepreneur  married
9    43       services  married
10   39       services  married

In [25]:
#Não sei porque deu erro, mas o item busca as colunas com o nome indicado
df.filter(items="job")

TypeError: Index(...) must be called with a collection of some kind, 'job' was passed

In [30]:
#retorna todas as colunas q tem alguma parte dastring passado no nome
df.filter(like="on").head()

   education   contact month  duration
0    primary  cellular   oct        79
1  secondary  cellular   may       220
2   tertiary  cellular   apr       185
3   tertiary   unknown   jun       199
4  secondary   unknown   may       226

In [31]:
#Usado pra expressões regulares, caso queira procurar algo mais complexo
df.filter(regex="[b-d]")

,job,education,default,balance,contact,day,duration,campaign,pdays,poutcome
0,unemployed,primary,no,1787,cellular,19,79,1,-1,unknown
1,services,secondary,no,4789,cellular,11,220,1,339,failure
2,management,tertiary,no,1350,cellular,16,185,1,330,failure
3,management,tertiary,no,1476,unknown,3,199,4,-1,unknown
4,blue-collar,secondary,no,0,unknown,5,226,1,-1,unknown
...,...,...,...,...,...,...,...,...,...,...
4516,services,secondary,no,-333,cellular,30,329,5,-1,unknown
4517,self-employed,tertiary,yes,-3313,unknown,9,153,1,-1,unknown
4518,technician,secondary,no,295,cellular,19,151,11,-1,unknown
4519,blue-collar,secondary,no,1137,cellular,6,129,4,211,other
4520,entrepreneur,tertiary,no,1136,cellular,3,345,2,249,other

In [44]:
#Uma maneira de filtra os dados
df[((df.education == 'secondary') & (df.age >= 50)) & (df.contact == "cellular")].loc[0:200]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
16,56,technician,married,secondary,no,4073,no,no,cellular,27,aug,239,5,-1,0,unknown,no
28,56,self-employed,married,secondary,no,784,no,yes,cellular,30,jul,149,2,-1,0,unknown,no
29,53,admin.,married,secondary,no,105,no,yes,cellular,21,aug,74,2,-1,0,unknown,no
32,59,management,married,secondary,no,42,no,no,cellular,21,nov,40,1,-1,0,unknown,no
42,52,blue-collar,married,secondary,no,1117,yes,no,cellular,13,may,365,1,-1,0,unknown,no
54,53,blue-collar,married,secondary,no,2231,yes,no,cellular,14,jul,272,3,-1,0,unknown,no
61,63,retired,married,secondary,no,415,yes,no,cellular,7,oct,323,1,-1,0,unknown,no
64,56,admin.,married,secondary,no,16873,no,no,cellular,7,oct,223,1,-1,0,unknown,no
65,51,blue-collar,divorced,secondary,no,203,yes,no,cellular,8,may,134,1,170,5,failure,no
94,57,blue-collar,married,secondary,no,14093,no,no,cellular,11,aug,231,5,-1,0,unknown,no
153,55,entrepreneur,married,secondary,no,8104,no,no,cellular,6,feb,213,2,-1,0,unknown,no
156,55,admin.,married,secondary,no,602,no,no,cellular,1,jun,324,3,90,2,success,yes
157,55,technician,married,secondary,no,273,yes,no,cellular,29,jan,84,3,183,3,failure,no
189,56,retired,married,secondary,no,-1206,yes,no,cellular,15,jun,382,2,-1,0,unknown,yes
195,57,retired,divorced,secondary,no,39,yes,no,cellular,30,jul,354,3,-1,0,unknown,no

In [52]:
#Outra forma de filtrar o data frame usando isin, porem quando usamos ele diretamente no dataFrame ele retorna uma lista de bool
df_filtrado = df.isin({"marital":["married"],"education":["secondary"], "contact":["cellular"], "job":["management", "blue-collar"]})

df[(df_filtrado.education) & (df_filtrado.contact) & (df_filtrado.job) & (df_filtrado.marital)]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
14,31,blue-collar,married,secondary,no,360,yes,yes,cellular,29,jan,89,1,241,1,failure,no
32,59,management,married,secondary,no,42,no,no,cellular,21,nov,40,1,-1,0,unknown,no
37,32,blue-collar,married,secondary,no,2089,yes,no,cellular,14,nov,132,1,-1,0,unknown,yes
38,33,management,married,secondary,no,3935,yes,no,cellular,6,may,765,1,342,2,failure,yes
42,52,blue-collar,married,secondary,no,1117,yes,no,cellular,13,may,365,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4455,50,blue-collar,married,secondary,no,181,yes,no,cellular,17,apr,599,2,-1,0,unknown,no
4466,61,management,married,secondary,no,967,no,no,cellular,20,aug,180,1,-1,0,unknown,no
4513,49,blue-collar,married,secondary,no,322,no,no,cellular,14,aug,356,2,-1,0,unknown,no
4514,38,blue-collar,married,secondary,no,1205,yes,no,cellular,20,apr,45,4,153,1,failure,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no

In [71]:
#Podemos agrupar os valores por calunas, neste comando pegamos os valores da coluna marital e seu respectivos valores da coluna age e calculamos a media dos valores
#como a coluna marital tem 3 valores possíveis tivemos apenas 3 linhas e suas respectivas medias, mas não oq aconteciria se uma coluna tivesse muitos valores possíveis
df[["marital", "age"]]. groupby("marital").mean()

                age
marital
divorced  45.475379
married   43.454415
single    33.927258