In [16]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(".//..//data//houses_to_rent.csv", sep=",")
df_nao_tratado = pd.read_csv(".//..//data//houses_to_rent.csv", sep=",")
df.head()

,Unnamed: 0,city,area,rooms,bathroom,parking spaces,floor,animal,furniture,hoa,rent amount,property tax,fire insurance,total
0,0,1,240,3,3,4,-,acept,furnished,R$0,"R$8,000","R$1,000",R$121,"R$9,121"
1,1,0,64,2,1,1,10,acept,not furnished,R$540,R$820,R$122,R$11,"R$1,493"
2,2,1,443,5,5,4,3,acept,furnished,"R$4,172","R$7,000","R$1,417",R$89,"R$12,680"
3,3,1,73,2,2,1,12,acept,not furnished,R$700,"R$1,250",R$150,R$16,"R$2,116"
4,4,1,19,1,1,0,-,not acept,not furnished,R$0,"R$1,200",R$41,R$16,"R$1,257"

In [4]:
df["rent amount_tratado"] = df["rent amount"].apply(lambda x: x.replace("R$", "")).apply(lambda x: x.replace(",",""))
df["ptoperty tax_tratado"] = df["property tax"].apply(lambda x: x.replace("R$", "")).apply(lambda x: x.replace(",",""))
df["fire insurance_tratado"] = df["fire insurance"].apply(lambda x: x.replace("R$", "")).apply(lambda x: x.replace(",",""))
df["total_tratado"] = df.total.apply(lambda x: x.replace("R$", "")).apply(lambda x: x.replace(",",""))


del df["rent amount"]
del df["property tax"]
del df["fire insurance"]
del df["total"]

In [5]:
df["hoa_tratado"] = df.hoa.apply(lambda x: x.replace("R$", "")).apply(lambda x: x.replace(",",""))
del df["hoa"]

df.head()

,Unnamed: 0,city,area,rooms,bathroom,parking spaces,floor,animal,furniture,rent amount_tratado,ptoperty tax_tratado,fire insurance_tratado,total_tratado,hoa_tratado
0,0,1,240,3,3,4,-,acept,furnished,8000,1000,121,9121,0
1,1,0,64,2,1,1,10,acept,not furnished,820,122,11,1493,540
2,2,1,443,5,5,4,3,acept,furnished,7000,1417,89,12680,4172
3,3,1,73,2,2,1,12,acept,not furnished,1250,150,16,2116,700
4,4,1,19,1,1,0,-,not acept,not furnished,1200,41,16,1257,0

In [6]:
df_nao_tratado.head()

,Unnamed: 0,city,area,rooms,bathroom,parking spaces,floor,animal,furniture,hoa,rent amount,property tax,fire insurance,total
0,0,1,240,3,3,4,-,acept,furnished,R$0,"R$8,000","R$1,000",R$121,"R$9,121"
1,1,0,64,2,1,1,10,acept,not furnished,R$540,R$820,R$122,R$11,"R$1,493"
2,2,1,443,5,5,4,3,acept,furnished,"R$4,172","R$7,000","R$1,417",R$89,"R$12,680"
3,3,1,73,2,2,1,12,acept,not furnished,R$700,"R$1,250",R$150,R$16,"R$2,116"
4,4,1,19,1,1,0,-,not acept,not furnished,R$0,"R$1,200",R$41,R$16,"R$1,257"

In [7]:
#trocando nomes das colunas com rename

colunas_originais = df.columns.to_list()

colunas_traduzidas = ["indices", "cidade", "area", "quartos", "banheiros", "vagas_garagem", "andar", "permitido_animais", "mobilhado", "aluguel", "taxas", "seguro_contra_incendio", "total", "hoa"]

dict_traduzido = dict(zip(colunas_originais, colunas_traduzidas))

new_df = df.rename(columns=dict_traduzido)

In [8]:
new_df["mobilhado"] = new_df["mobilhado"].apply(lambda x: x.replace("furnished", "mobilhado"))

new_df.head()

,indices,cidade,area,quartos,banheiros,vagas_garagem,andar,permitido_animais,mobilhado,aluguel,taxas,seguro_contra_incendio,total,hoa
0,0,1,240,3,3,4,-,acept,mobilhado,8000,1000,121,9121,0
1,1,0,64,2,1,1,10,acept,not mobilhado,820,122,11,1493,540
2,2,1,443,5,5,4,3,acept,mobilhado,7000,1417,89,12680,4172
3,3,1,73,2,2,1,12,acept,not mobilhado,1250,150,16,2116,700
4,4,1,19,1,1,0,-,not acept,not mobilhado,1200,41,16,1257,0

In [13]:
new_df["mobilhado"] = new_df["mobilhado"].apply(lambda x: x.replace("not mobilhado", "nao_mobilhado"))
new_df

,indices,cidade,area,quartos,banheiros,vagas_garagem,andar,permitido_animais,mobilhado,aluguel,taxas,seguro_contra_incendio,total,hoa
0,0,1,240,3,3,4,-,sim,mobilhado,8000,1000,121,9121,0
1,1,0,64,2,1,1,10,sim,nao_mobilhado,820,122,11,1493,540
2,2,1,443,5,5,4,3,sim,mobilhado,7000,1417,89,12680,4172
3,3,1,73,2,2,1,12,sim,nao_mobilhado,1250,150,16,2116,700
4,4,1,19,1,1,0,-,nao,nao_mobilhado,1200,41,16,1257,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,6075,1,50,2,1,1,2,sim,nao_mobilhado,1150,0,15,1585,420
6076,6076,1,84,2,2,1,16,nao,mobilhado,2900,63,37,3768,768
6077,6077,0,48,1,1,0,13,sim,nao_mobilhado,950,42,13,1255,250
6078,6078,1,160,3,2,2,-,nao,nao_mobilhado,3500,250,53,3803,0
6079,6079,1,60,2,1,1,4,sim,mobilhado,1900,0,25,2414,489

In [10]:
new_df["permitido_animais"] = new_df["permitido_animais"].apply(lambda x: x.replace("acept", "sim"))
new_df["permitido_animais"] = new_df["permitido_animais"].apply(lambda x: x.replace("not sim", "nao"))

new_df

,indices,cidade,area,quartos,banheiros,vagas_garagem,andar,permitido_animais,mobilhado,aluguel,taxas,seguro_contra_incendio,total,hoa
0,0,1,240,3,3,4,-,sim,mobilhado,8000,1000,121,9121,0
1,1,0,64,2,1,1,10,sim,not mobilhado,820,122,11,1493,540
2,2,1,443,5,5,4,3,sim,mobilhado,7000,1417,89,12680,4172
3,3,1,73,2,2,1,12,sim,not mobilhado,1250,150,16,2116,700
4,4,1,19,1,1,0,-,nao,not mobilhado,1200,41,16,1257,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,6075,1,50,2,1,1,2,sim,not mobilhado,1150,0,15,1585,420
6076,6076,1,84,2,2,1,16,nao,mobilhado,2900,63,37,3768,768
6077,6077,0,48,1,1,0,13,sim,not mobilhado,950,42,13,1255,250
6078,6078,1,160,3,2,2,-,nao,not mobilhado,3500,250,53,3803,0
6079,6079,1,60,2,1,1,4,sim,mobilhado,1900,0,25,2414,489

In [11]:
#Podemos utilizar o assigned para inserir colunas no data frame, não altera o dataframe original, retorna uma copia.
new_df.assign(total_comodos = lambda x: x.quartos + x.banheiros).loc[:10, ["quartos", "banheiros", "total_comodos"]]

    quartos  banheiros  total_comodos
0         3          3              6
1         2          1              3
2         5          5             10
3         2          2              4
4         1          1              2
5         1          1              2
6         1          1              2
7         2          2              4
8         3          1              4
9         1          1              2
10        1          1              2

In [14]:
new_df

,indices,cidade,area,quartos,banheiros,vagas_garagem,andar,permitido_animais,mobilhado,aluguel,taxas,seguro_contra_incendio,total,hoa
0,0,1,240,3,3,4,-,sim,mobilhado,8000,1000,121,9121,0
1,1,0,64,2,1,1,10,sim,nao_mobilhado,820,122,11,1493,540
2,2,1,443,5,5,4,3,sim,mobilhado,7000,1417,89,12680,4172
3,3,1,73,2,2,1,12,sim,nao_mobilhado,1250,150,16,2116,700
4,4,1,19,1,1,0,-,nao,nao_mobilhado,1200,41,16,1257,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,6075,1,50,2,1,1,2,sim,nao_mobilhado,1150,0,15,1585,420
6076,6076,1,84,2,2,1,16,nao,mobilhado,2900,63,37,3768,768
6077,6077,0,48,1,1,0,13,sim,nao_mobilhado,950,42,13,1255,250
6078,6078,1,160,3,2,2,-,nao,nao_mobilhado,3500,250,53,3803,0
6079,6079,1,60,2,1,1,4,sim,mobilhado,1900,0,25,2414,489